# Generated by Django 5.2.4 on 2025-07-20 14:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the forum section')),
            ],
            options={
                'verbose_name': 'Forum Index Page',
                'verbose_name_plural': 'Forum Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ForumLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Community Forum', max_length=255)),
                ('hero_subtitle', models.CharField(default='Join our community to discuss Python programming, share knowledge, and get help', max_length=500)),
                ('content', wagtail.fields.StreamField([('announcement', 3), ('recent_topics', 7), ('forum_activity', 10), ('rich_text', 1), ('html', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Important')]}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1), ('announcement_type', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Recent Forum Topics'}), 5: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'max_value': 20, 'min_value': 1}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [], 'help_text': 'Filter topics from specific forum', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('num_topics', 5), ('forum_filter', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Forum Activity'}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 10: ('wagtail.blocks.StructBlock', [[('title', 8), ('show_topics', 9), ('show_posts', 9), ('show_members', 9), ('show_online', 9)]], {}), 11: ('wagtail.blocks.RawHTMLBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Forum Landing Page',
                'verbose_name_plural': 'Forum Landing Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
