# Generated by Django 5.2.4 on 2025-07-21 00:05

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
        ('forum_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('scroll_depth', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_read_post', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('first_read', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='forum_conversation.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Progress',
                'verbose_name_plural': 'Reading Progress',
                'indexes': [models.Index(fields=['user', 'completed'], name='forum_integ_user_id_23c96b_idx'), models.Index(fields=['topic'], name='forum_integ_topic_i_a1d1d5_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='TrustLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'New User'), (1, 'Basic User'), (2, 'Member'), (3, 'Regular'), (4, 'Leader')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('posts_read', models.IntegerField(default=0)),
                ('topics_viewed', models.IntegerField(default=0)),
                ('time_read', models.DurationField(default=datetime.timedelta(0))),
                ('posts_created', models.IntegerField(default=0)),
                ('topics_created', models.IntegerField(default=0)),
                ('likes_given', models.IntegerField(default=0)),
                ('likes_received', models.IntegerField(default=0)),
                ('days_visited', models.IntegerField(default=0)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Level',
                'verbose_name_plural': 'Trust Levels',
                'indexes': [models.Index(fields=['level'], name='forum_integ_level_f1a7fa_idx'), models.Index(fields=['last_visit_date'], name='forum_integ_last_vi_5f338f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('posts_read_today', models.IntegerField(default=0)),
                ('topics_viewed_today', models.IntegerField(default=0)),
                ('time_spent_reading', models.DurationField(default=datetime.timedelta(0))),
                ('posts_created_today', models.IntegerField(default=0)),
                ('likes_given_today', models.IntegerField(default=0)),
                ('first_visit_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'indexes': [models.Index(fields=['date'], name='forum_integ_date_066624_idx'), models.Index(fields=['user', 'date'], name='forum_integ_user_id_2e5545_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
