# Generated by Django 5.2.4 on 2025-07-21 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_integration', '0002_readingprogress_trustlevel_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='active_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='topics_completed',
            field=models.IntegerField(default=0),
        ),
    ]
