# Generated by Django 5.2.4 on 2025-08-12 03:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
        ('forum_integration', '0005_add_badge_gamification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('code', 6), ('video', 10), ('quote', 13), ('callout', 17), ('embed', 20), ('list', 24)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'code', 'superscript', 'subscript'], 'help_text': 'Rich text paragraph with basic formatting'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section heading'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload or select an image'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON'), ('yaml', 'YAML'), ('cpp', 'C++'), ('java', 'Java'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby')]}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Your code here...'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption or title', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube, Vimeo, or direct video URL. YouTube URLs will be auto-embedded.'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional video title', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional video description', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('video_url', 7), ('title', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'The quote text'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Source or attribution', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 11), ('source', 12)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Important/Danger'), ('tip', 'Tip'), ('note', 'Note')]}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title', 'required': False}), 16: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Callout content'}), 17: ('wagtail.blocks.StructBlock', [[('type', 14), ('title', 15), ('text', 16)]], {}), 18: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Paste embed code from YouTube, CodePen, JSFiddle, etc.'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('embed_code', 18), ('caption', 19)]], {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ul', 'Bulleted List'), ('ol', 'Numbered List')]}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'List item'}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('list_type', 21), ('items', 23)]], {})}, help_text='Rich content for this forum post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rich_content', to='forum_conversation.post')),
            ],
            options={
                'verbose_name': 'Rich Forum Post',
                'verbose_name_plural': 'Rich Forum Posts',
            },
        ),
    ]
