# Generated by Django 5.2.7 on 2025-10-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_forum_id'),
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
        ('forum_integration', '0005_add_badge_gamification_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💬', help_text='Emoji or icon class (e.g., 💬 or fa-comments)', max_length=50)),
                ('color', models.CharField(default='bg-blue-500', help_text='Tailwind color class (e.g., bg-blue-500)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='forum.forum')),
            ],
            options={
                'verbose_name': 'Forum Customization',
                'verbose_name_plural': 'Forum Customizations',
            },
        ),
        migrations.CreateModel(
            name='PostEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('previous_content', models.TextField(help_text='Content before this edit')),
                ('new_content', models.TextField(help_text='Content after this edit')),
                ('edit_reason', models.CharField(blank=True, help_text='Optional reason for the edit', max_length=200)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_edits', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='forum_conversation.post')),
            ],
            options={
                'verbose_name': 'Post Edit History',
                'verbose_name_plural': 'Post Edit Histories',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['post', '-edited_at'], name='forum_integ_post_id_eef988_idx')],
            },
        ),
    ]
