# Generated by Django 5.2.7 on 2025-10-19 03:50

import apps.users.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_integration', '0006_forumcustomization_postedithistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Custom badge image (max 2 MB, JPG/PNG/GIF/WEBP)', null=True, upload_to=apps.users.validators.SecureBadgeImageUpload(), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.users.validators.validate_badge_image_file_size, apps.users.validators.validate_image_dimensions, apps.users.validators.validate_image_content, apps.users.validators.validate_mime_type]),
        ),
        migrations.AddIndex(
            model_name='trustlevel',
            index=models.Index(fields=['level', '-posts_created'], name='trustlevel_level_posts_idx'),
        ),
        migrations.AddIndex(
            model_name='trustlevel',
            index=models.Index(fields=['level', '-likes_received'], name='trustlevel_level_likes_idx'),
        ),
        migrations.AddIndex(
            model_name='trustlevel',
            index=models.Index(fields=['-posts_created'], name='trustlevel_posts_idx'),
        ),
    ]
