# Generated by Django 5.2.7 on 2025-10-20 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='poster_username',
            field=models.CharField(blank=True, help_text='Cached username for display when poster is deleted', max_length=155, null=True, verbose_name='Poster Username (cached)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='User who created this post (NULL if user deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='User who created this topic (NULL if user deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Poster'),
        ),
    ]
