version: '3.8'

services:
  # Redis cache service
  redis:
    image: redis:7-alpine
    container_name: learning_studio_redis
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - learning_studio_network
    restart: unless-stopped

  # PostgreSQL database (optional - for production-like environment)
  postgres:
    image: postgres:15-alpine
    container_name: learning_studio_db
    environment:
      POSTGRES_DB: ${DB_NAME:-learning_studio}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - learning_studio_network
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  learning_studio_network:
    driver: bridge
