# Generated by Django 5.2.4 on 2025-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_discussion_discussionreply_learningbuddy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_format',
            field=models.CharField(choices=[('plain', 'Plain Text'), ('markdown', 'Markdown'), ('structured', 'Structured Blocks')], default='plain', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='enable_structured_content',
            field=models.BooleanField(default=False, help_text='Use structured content blocks instead of plain text'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='structured_content',
            field=models.JSONField(blank=True, default=list, help_text='Structured content blocks for enhanced lesson delivery'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Main lesson content (legacy field)'),
        ),
    ]
