# Generated by Django 5.2.7 on 2025-10-19 03:50

import apps.users.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_add_structured_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Course banner image (max 10 MB, JPG/PNG/WEBP, 50x50 to 2048x2048)', null=True, upload_to=apps.users.validators.SecureCourseImageUpload('course_banners'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.users.validators.validate_course_image_file_size, apps.users.validators.validate_image_dimensions, apps.users.validators.validate_image_content, apps.users.validators.validate_mime_type]),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Course thumbnail (max 10 MB, JPG/PNG/WEBP, 50x50 to 2048x2048)', null=True, upload_to=apps.users.validators.SecureCourseImageUpload('course_thumbnails'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.users.validators.validate_course_image_file_size, apps.users.validators.validate_image_dimensions, apps.users.validators.validate_image_content, apps.users.validators.validate_mime_type]),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'difficulty_level'], name='course_pub_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured', '-created_at'], name='course_feat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_published'], name='course_cat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_published'], name='course_instr_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='course_created_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', '-enrolled_at'], name='enrollment_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'completed'], name='enrollment_user_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', '-enrolled_at'], name='enrollment_course_date_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', '-last_activity'], name='enrollment_user_act_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'order'], name='exercise_lesson_order_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['lesson', 'is_published'], name='exercise_lesson_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['difficulty_level', 'is_published'], name='exercise_diff_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['exercise_type', 'is_published'], name='exercise_type_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', 'is_featured', '-created_at'], name='path_pub_feat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', 'difficulty_level'], name='path_pub_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['creator', 'is_published'], name='path_creator_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lesson_course_order_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'is_published'], name='lesson_course_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'lesson_type'], name='lesson_course_type_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-started_at'], name='session_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['lesson', '-started_at'], name='session_lesson_start_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'lesson', '-started_at'], name='session_user_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'completed_lesson'], name='session_user_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='progress_user_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', '-last_accessed'], name='progress_user_access_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['lesson', 'completed'], name='progress_lesson_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'bookmarked'], name='progress_user_book_idx'),
        ),
    ]
