# Generated by Django 5.2.4 on 2025-08-02 02:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_exercisepage_learningindexpage_learningobjective_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePlaygroundPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Description of the playground and its features')),
                ('default_code', models.TextField(blank=True, help_text='Default code to show when the playground loads')),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL')], default='python', help_text='Default programming language for the playground', max_length=50)),
                ('features', wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon class', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2)]], {})})),
                ('code_examples', wagtail.fields.StreamField([('example', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')]}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('language', 2), ('code', 1), ('category', 3)]], {})})),
                ('shortcuts', wagtail.fields.StreamField([('shortcut', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., Ctrl+S', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('keys', 0), ('description', 1)]], {})})),
                ('enable_file_operations', models.BooleanField(default=True, help_text='Allow save/load functionality')),
                ('enable_auto_save', models.BooleanField(default=True, help_text='Enable automatic saving of code')),
                ('enable_multiple_languages', models.BooleanField(default=True, help_text='Allow switching between programming languages')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
