# Generated by Django 5.2.7 on 2025-10-14 20:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_exercisepage_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepbasedexercisepage',
            name='exercise_steps',
            field=wagtail.fields.StreamField([('exercise_step', 10)], block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Step order number'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Step title'}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Step instructions and context'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('code', 'Code Editor'), ('fill_blank', 'Fill in the Blanks'), ('multiple_choice', 'Multiple Choice'), ('quiz', 'Quiz')]}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Code template with {{BLANK_N}} for fill-in-blank', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON solutions: {"1": "answer1", "2": "answer2"}', 'required': False}), 6: ('wagtail.blocks.IntegerBlock', (), {'default': 10, 'help_text': 'Points for this step'}), 7: ('wagtail.blocks.TextBlock', (), {'default': "Great job! You've completed this step.", 'help_text': 'Message shown on step completion'}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional hint for this step', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'JSON array of progressive hints: [{"level": 1, "type": "conceptual", "title": "...", "content": "...", "triggerTime": 30, "triggerAttempts": 0}]', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('step_number', 0), ('title', 1), ('description', 2), ('exercise_type', 3), ('template', 4), ('solutions', 5), ('points', 6), ('success_message', 7), ('hint', 8), ('progressive_hints', 9)]], {})}),
        ),
    ]
