# Generated by Django 5.2.7 on 2025-10-19 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_stepbasedexercisepage_exercise_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='blogcat_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='wagtailcourseenrollment',
            index=models.Index(fields=['user', '-enrolled_at'], name='wgtl_enroll_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wagtailcourseenrollment',
            index=models.Index(fields=['user', 'completed'], name='wgtl_enroll_user_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='wagtailcourseenrollment',
            index=models.Index(fields=['course', '-enrolled_at'], name='wgtl_enroll_course_date_idx'),
        ),
        migrations.AddIndex(
            model_name='wagtailcourseenrollment',
            index=models.Index(fields=['user', '-last_activity'], name='wgtl_enroll_user_act_idx'),
        ),
    ]
