# Generated by Django 5.2.7 on 2025-10-20 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add database indexes to Wagtail Page models for improved query performance.

    PRODUCTION DEPLOYMENT NOTES:
    =============================
    For PostgreSQL production environments, replace migrations.AddIndex with
    AddIndexConcurrently to avoid table locks:

    1. Import: from django.contrib.postgres.operations import AddIndexConcurrently
    2. Set: atomic = False (at class level)
    3. Replace all migrations.AddIndex with AddIndexConcurrently

    This ensures zero-downtime deployments in production while allowing
    fast execution in development (SQLite).
    """

    dependencies = [
        ('blog', '0009_blogcategory_blogcat_slug_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # CoursePage indexes
        migrations.AddIndex(
            model_name='coursepage',
            index=models.Index(fields=['featured'], name='course_page_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepage',
            index=models.Index(fields=['difficulty_level', 'is_free'], name='course_page_diff_free_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepage',
            index=models.Index(fields=['featured', 'difficulty_level'], name='course_page_feat_diff_idx'),
        ),

        # ExercisePage indexes
        migrations.AddIndex(
            model_name='exercisepage',
            index=models.Index(fields=['exercise_type', 'difficulty'], name='exercise_page_type_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisepage',
            index=models.Index(fields=['programming_language', 'difficulty'], name='exercise_page_lang_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisepage',
            index=models.Index(fields=['sequence_number'], name='exercise_page_seq_idx'),
        ),

        # StepBasedExercisePage indexes
        migrations.AddIndex(
            model_name='stepbasedexercisepage',
            index=models.Index(fields=['difficulty'], name='step_exercise_page_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='stepbasedexercisepage',
            index=models.Index(fields=['sequence_number'], name='step_exercise_page_seq_idx'),
        ),
    ]
