# Generated by Django 5.2.7 on 2025-10-19 03:50

import apps.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, help_text='Achievement icon (max 5 MB, JPG/PNG/GIF/WEBP)', null=True, upload_to=apps.users.validators.SecureAchievementIconUpload(), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.users.validators.validate_image_file_size, apps.users.validators.validate_image_dimensions, apps.users.validators.validate_image_content, apps.users.validators.validate_mime_type]),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='icon',
            field=models.ImageField(blank=True, help_text='Language icon (max 5 MB, JPG/PNG/GIF/WEBP)', null=True, upload_to=apps.users.validators.SecureIconUpload(), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.users.validators.validate_image_file_size, apps.users.validators.validate_image_dimensions, apps.users.validators.validate_image_content, apps.users.validators.validate_mime_type]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5 MB, JPG/PNG/GIF/WEBP, 50x50 to 2048x2048)', null=True, upload_to=apps.users.validators.SecureAvatarUpload(), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.users.validators.validate_image_file_size, apps.users.validators.validate_image_dimensions, apps.users.validators.validate_image_content, apps.users.validators.validate_mime_type]),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['skill_level', 'profile_visibility'], name='profile_skill_vis_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['profile_visibility', '-total_courses_completed'], name='profile_vis_courses_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['profile_visibility', '-total_exercises_solved'], name='profile_vis_exercises_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-created_at'], name='profile_created_idx'),
        ),
    ]
