# Generated by Django 5.2.4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscourseGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discourse_group_name', models.CharField(help_text='Discourse group name', max_length=255)),
                ('auto_sync', models.BooleanField(default=True, help_text='Automatically sync group membership')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discourse_mapping', to='auth.group')),
            ],
            options={
                'verbose_name': 'Discourse Group Mapping',
                'verbose_name_plural': 'Discourse Group Mappings',
            },
        ),
        migrations.CreateModel(
            name='DiscourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discourse_user_id', models.CharField(help_text='Discourse user ID', max_length=255, unique=True)),
                ('discourse_username', models.CharField(help_text='Username in Discourse', max_length=255)),
                ('last_sync', models.DateTimeField(auto_now=True, help_text='Last synchronization timestamp')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether user sync is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discourse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discourse User',
                'verbose_name_plural': 'Discourse Users',
                'indexes': [
                    models.Index(fields=['discourse_user_id'], name='discourse_ss_discour_e0c5b8_idx'),
                    models.Index(fields=['discourse_username'], name='discourse_ss_discour_bf4dd0_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DiscourseSsoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('login', 'SSO Login'), ('register', 'SSO Registration'), ('sync', 'User Sync'), ('error', 'SSO Error')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('nonce', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discourse_sso_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discourse SSO Log',
                'verbose_name_plural': 'Discourse SSO Logs',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['timestamp'], name='discourse_ss_timesta_88e5d3_idx'),
                    models.Index(fields=['user', 'timestamp'], name='discourse_ss_user_id_a1bbb1_idx'),
                    models.Index(fields=['action', 'timestamp'], name='discourse_ss_action_bbba17_idx'),
                ],
            },
        ),
    ]