# Generated by Django 5.2.4 on 2025-07-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_sso', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discoursessolog',
            new_name='discourse_s_timesta_769bdd_idx',
            old_name='discourse_ss_timesta_88e5d3_idx',
        ),
        migrations.RenameIndex(
            model_name='discoursessolog',
            new_name='discourse_s_user_id_a29bd7_idx',
            old_name='discourse_ss_user_id_a1bbb1_idx',
        ),
        migrations.RenameIndex(
            model_name='discoursessolog',
            new_name='discourse_s_action_adf017_idx',
            old_name='discourse_ss_action_bbba17_idx',
        ),
        migrations.RenameIndex(
            model_name='discourseuser',
            new_name='discourse_s_discour_43a92c_idx',
            old_name='discourse_ss_discour_e0c5b8_idx',
        ),
        migrations.RenameIndex(
            model_name='discourseuser',
            new_name='discourse_s_discour_5464d5_idx',
            old_name='discourse_ss_discour_bf4dd0_idx',
        ),
    ]
