name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Run only on code changes, not documentation
    paths:
      - "apps/**/*.py"
      - "learning_community/**/*.py"
      - "frontend/**/*.{js,jsx,ts,tsx}"
      - "*.py"
      - "requirements*.txt"
      - "setup.py"
      - "pyproject.toml"
      - "!**/*.md"

jobs:
  claude-review:
    # SECURITY: Only run for trusted contributors (OWNER, MEMBER, COLLABORATOR)
    if: |
      github.event.pull_request.author_association == 'OWNER' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'COLLABORATOR'

    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Concurrency control: Cancel stale reviews when new commits are pushed
    concurrency:
      group: claude-review-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper PR context

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Review this pull request following CLAUDE.md code review guidelines.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Be constructive and helpful. Use `gh pr comment` to post your review.

          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*),Read,Grep"'
